# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sharePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
