# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_auto_20180311_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='datedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='month')),
            ],
        ),
        migrations.RenameField(
            model_name='shareprice',
            old_name='data',
            new_name='date',
        ),
    ]
